[package]
name = "memscan"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
core_detect = "1.0.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "find_first"
harness = false

[profile.release]
lto = true
opt-level = 3
panic = "abort"
debug = false
