[workspace]
members = ["memscan", "memscan-gui", "random_memory"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
core_detect = "1.0.0"
criterion = "0.3"

[profile.release]
lto = true
opt-level = 3
panic = "abort"
debug = false
