[package]
name = "memscan"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
core_detect.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "find_first"
harness = false
